# Generated by Django 3.0.7 on 2020-07-15 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Son',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('titre_image', models.ImageField(default='default.jpg', upload_to='son_pics')),
                ('poster_image', models.ImageField(default='default.jpg', upload_to='son_poster')),
                ('resume', models.TextField(blank=True)),
                ('realisation', models.TextField(blank=True)),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
                ('youtube', models.URLField(blank=True)),
                ('deezer', models.URLField(blank=True)),
                ('spotify', models.URLField(blank=True)),
                ('en_avant', models.BooleanField(default=False)),
            ],
        ),
    ]
