# Generated by Django 3.0.7 on 2020-06-24 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Son',
            fields=[
                ('titre', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('titre_image', models.ImageField(upload_to='son_pics')),
                ('resume', models.TextField()),
                ('realisation', models.TextField()),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
                ('youtube', models.URLField()),
                ('deezer', models.URLField()),
                ('spotify', models.URLField()),
            ],
        ),
    ]
