# Generated by Django 3.0.7 on 2020-06-24 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='son',
            name='poster_image',
            field=models.ImageField(default='default.jpg', upload_to='son_poster'),
        ),
        migrations.AlterField(
            model_name='son',
            name='titre_image',
            field=models.ImageField(default='default.jpg', upload_to='son_pics'),
        ),
    ]
