# Generated by Django 3.0.7 on 2020-07-15 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20200715_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='son',
            name='poster_image',
            field=models.ImageField(default='default.jpg', upload_to='img/poster_image'),
        ),
        migrations.AlterField(
            model_name='son',
            name='titre_image',
            field=models.ImageField(default='default.jpg', upload_to='img/tire_image'),
        ),
    ]
