# Generated by Django 3.0.7 on 2020-06-24 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20200624_1826'),
    ]

    operations = [
        migrations.AddField(
            model_name='son',
            name='en_avant',
            field=models.BooleanField(default=False),
        ),
    ]
