# Generated by Django 3.0.7 on 2020-07-07 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_son_en_avant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='son',
            name='realisation',
            field=models.TextField(default="Aucun pour l'instant"),
        ),
        migrations.AlterField(
            model_name='son',
            name='resume',
            field=models.TextField(default="Aucun pour l'instant"),
        ),
    ]
