# Generated by Django 3.0.7 on 2020-07-24 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20200715_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='son',
            name='poster_image',
            field=models.ImageField(default='default.jpg', upload_to='poster_image'),
        ),
        migrations.AlterField(
            model_name='son',
            name='titre',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='son',
            name='titre_image',
            field=models.ImageField(default='default.jpg', upload_to='tire_image'),
        ),
    ]
