# Generated by Django 3.0.7 on 2020-07-07 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_auto_20200707_2240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='son',
            name='deezer',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='son',
            name='spotify',
            field=models.URLField(blank=True),
        ),
    ]
