# Generated by Django 3.0.7 on 2020-07-24 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_auto_20200724_2154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='son',
            name='deezer',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='son',
            name='realisation',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='son',
            name='resume',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='son',
            name='spotify',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='son',
            name='youtube',
            field=models.URLField(blank=True),
        ),
    ]
