# Generated by Django 3.0.7 on 2020-07-27 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_auto_20200724_2202'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnAvantStyle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banniere_titre', models.CharField(default='NOTRE PREMIER CLIP', max_length=255)),
                ('banniere_couleur', models.CharField(default='#262626', max_length=255)),
                ('banniere_background', models.CharField(default='#FEC959', max_length=255)),
                ('couleur_corps', models.CharField(default='#FEC959', max_length=255)),
            ],
        ),
    ]
