# Generated by Django 3.0.7 on 2020-07-27 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_enavantstyle'),
    ]

    operations = [
        migrations.AddField(
            model_name='enavantstyle',
            name='background_corps',
            field=models.CharField(default='#8E0303', max_length=255),
        ),
    ]
