# Generated by Django 3.0.7 on 2020-08-06 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_enavantstyle_background_corps'),
    ]

    operations = [
        migrations.AlterField(
            model_name='son',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
